# Generated by Django 5.2.8 on 2025-11-13 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseball", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="player",
            options={
                "ordering": ["-hits", "-home_runs"],
                "verbose_name": "Player",
                "verbose_name_plural": "Players",
            },
        ),
    ]
